#  Global variables to be used in all the templates.
global:
  projectName: "{{ .data.projectName }}"
  projectRepository: "{{ .data.projectRepository }}"

# Structure of folders and files that will be generated
structure:
  {{.data.baseDir}}:
    index.ts:
      template: templates/Index.gtpl
    providers:
      http:
        index.ts:
          template: templates/ProviderExporter.gtpl

        http_provider.ts:
          template: templates/HttpProvider.gtpl
        http_provider_interface.ts:
          template: templates/HttpProviderInterface.gtpl
        dto.ts:
          template: templates/HttpProviderDTO.gtpl