{{$base := . }}

#  Global variables to be used in all the templates.
global:
  projectName: "myproject"
  projectRepository: "gihub.com/arthurbcp/ts-test-services"
  projectDescription: "This is a sample project"

# Structure of folders and files that will be generated
structure:
  src:
      index.ts:
        template: Index.gtpl
      providers:
        http:
          index.ts:
            template: ProviderExporter.gtpl
            
          http_provider.ts:
            template: HttpProvider.gtpl
          http_provider_interface.ts:
            template: HttpProviderInterface.gtpl
          dto.ts:
            template: HttpProviderDTO.gtpl
      dto:
        index.ts:
          template: DTOExporter.gtpl
          data: 
            {{range $name, $prop := $base.definitions }}{{ if eq $prop.type "object" }}
              - {{ $name }}
            {{end}}{{end}}
            
        {{range $name, $prop := $base.definitions }}{{ if eq $prop.type "object" }}{{ toSnakeCase $name }}.ts:
          template: DTO.gtpl
          Includes:
            - TypeResolver.gtpl
          data:
            name: {{ $name }}
            {{ range toYaml . }}{{ . }}
            {{end}}
        {{end}}{{end}}
      services:
        builder.ts:
          template: ServiceBuilder.gtpl
          data:
            {{range $base.tags}}
            - {{.name}} 
            {{end}}
        index.ts:
          template: ServiceExporter.gtpl
          data:
            {{range $base.tags}}
            - {{.name}}
            {{end}}

        {{range $base.tags}}{{toSnakeCase .name}}:
          {{$tag := .}}
          service.ts:
            template: Service.gtpl
            Includes:
              - TypeResolver.gtpl
              - ResponseTypeResolver.gtpl
            data:
              name: {{$tag.name}}
              description:  {{$tag.description}}
              operations:
              {{range $path, $req := getPathsByTag $base.paths $tag.name}}
                {{$path}}: 
                    {{range toYaml $req}}{{.}}
                    {{end}}
              {{end}}
        {{end}}

  package.json:
    template: PackageJson.gtpl
  tsconfig.json:
    template: TsConfig.gtpl
