{{$base := .data.apiData}}
structure:
      dto:
        index.ts:
          template: DTOExporter.gtpl
          data: 
            {{range $name, $prop := $base.definitions }}{{ if eq $prop.type "object" }}
              - {{ $name }}
            {{end}}{{end}}
            
        {{range $name, $prop := $base.definitions }}{{ if eq $prop.type "object" }}{{ toSnakeCase $name }}.ts:
          template: DTO.gtpl
          includes:
            - TypeResolver.gtpl
          data:
            name: {{ $name }}
            {{ range toYaml . }}{{ . }}
            {{end}}
        {{end}}{{end}}
      services:
        builder.ts:
          template: ServiceBuilder.gtpl
          data:
            {{range $base.tags}}
            - {{.name}} 
            {{end}}
        index.ts:
          template: ServiceExporter.gtpl
          data:
            {{range $base.tags}}
            - {{.name}}
            {{end}}

        {{range $base.tags}}{{toSnakeCase .name}}:
          {{$tag := .}}
          service.ts:
            template: Service.gtpl
            includes:
              - TypeResolver.gtpl
              - ResponseTypeResolver.gtpl
            data:
              name: {{$tag.name}}
              description:  {{$tag.description}}
              operations:
              {{range $path, $req := getPathsByTag $base.paths $tag.name}}
                {{$path}}: 
                    {{range toYaml $req}}{{.}}
                    {{end}}
              {{end}}
        {{end}}
